import { useState } from "react";

const C = {
  bg: "#0D1B2A",
  bgMid: "#1B2A3B",
  bgCard: "#162030",
  cyan: "#00D4FF",
  purple: "#7B61FF",
  mint: "#00E5A0",
  coral: "#FF6B6B",
  gold: "#FFD700",
  white: "#FFFFFF",
  light: "#B0C4DE",
  muted: "#607B96",
};    // ============== THIS IS THE NEW CODE YOU PROVIDED ==============
// I renamed it from SFSSInfographic to VisualStoryboardSection
const VisualStoryboardSection = () => {
  return (
    <div className="max-w-5xl mx-auto p-8 bg-slate-50 text-slate-800 font-sans shadow-xl rounded-xl">
      {/* Title Section */}
      <header className="text-center mb-10">
        <h1 className="text-4xl font-extrabold text-indigo-700 tracking-tight flex items-center justify-center gap-3">
          <span role="img" aria-label="palette">🎨</span> 
          Unlocking Streaming Function Secret Sharing (SFSS)
        </h1>
        <p className="text-lg text-slate-500 mt-2 font-medium">A visual guide to secure, low-overhead cryptographic streaming.</p>
      </header>

      {/* The Visual Legend */}
      <section className="bg-white p-6 rounded-lg shadow-sm border border-slate-200 mb-8">
        <h2 className="text-xl font-bold text-slate-700 mb-4 flex items-center gap-2">
          <span role="img" aria-label="key">🔑</span> The Visual Legend
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="flex items-center gap-3 p-3 bg-blue-50 rounded-md">
            <span className="text-2xl">📄</span>
            <div>
              <p className="font-semibold text-sm">Message (m<sub>j</sub>)</p>
              <p className="text-xs text-slate-600">The raw, secret data the client wants to send.</p>
            </div>
          </div>
          <div className="flex items-center gap-3 p-3 bg-gray-100 rounded-md">
            <span className="text-2xl">🌫️</span>
            <div>
              <p className="font-semibold text-sm">Static Mask (R)</p>
              <p className="text-xs text-slate-600">The random noise generated by the PRF.</p>
            </div>
          </div>
          <div className="flex items-center gap-3 p-3 bg-indigo-50 rounded-md">
            <span className="text-2xl">📦</span>
            <div>
              <p className="font-semibold text-sm">Ciphertext Box (c<sub>j</sub>)</p>
              <p className="text-xs text-slate-600">c<sub>j</sub> = m<sub>j</sub> + R</p>
            </div>
          </div>
          <div className="flex items-center gap-3 p-3 bg-purple-50 rounded-md">
            <span className="text-2xl">⚙️</span>
            <div>
              <p className="font-semibold text-sm">Server Keys</p>
              <p className="text-xs text-slate-600">Reusable half-Rulebooks on Server 0 & 1.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Setup & Streaming Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-10">
        {/* Part 1 */}
        <section className="bg-indigo-600 text-white p-6 rounded-lg shadow-md relative overflow-hidden">
          <h3 className="text-xl font-bold mb-3 flex items-center gap-2">
            <span role="img" aria-label="tools">🛠️</span> PART 1: One-Time Setup
          </h3>
          <div className="mb-4 text-sm bg-indigo-700 p-3 rounded text-indigo-100">
            <strong>Visual:</strong> A Client standing in front of two Servers.
          </div>
          <p className="text-sm mb-3">
            The Client creates a static Rulebook (the Function). They split the Rulebook in half and give <strong>Key 0 to Server 0</strong> and <strong>Key 1 to Server 1</strong>. The Client keeps a Secret Master Stamp (Encryption Key).
          </p>
          <blockquote className="border-l-4 border-indigo-300 pl-3 italic text-indigo-200 text-sm mt-4">
            "The rule is permanently locked. No more heavy keys need to be sent!"
          </blockquote>
        </section>

        {/* Part 2 */}
        <section className="bg-indigo-600 text-white p-6 rounded-lg shadow-md">
          <h3 className="text-xl font-bold mb-3 flex items-center gap-2">
            <span role="img" aria-label="box">📦</span> PART 2: Streaming Encryption
          </h3>
          <div className="mb-4 text-sm bg-indigo-700 p-3 rounded text-indigo-100">
            <strong>Visual:</strong> Client places Message (m<sub>j</sub>) into a Box, covers it in Static Mask (R), adds Counter tag (j).
          </div>
          <p className="text-sm mb-3">
            The Client sends this single locked Box (c<sub>j</sub>) to the Servers.
          </p>
          <div className="bg-white text-indigo-900 font-mono text-center py-2 rounded font-bold mt-4 shadow-inner">
            c<sub>j</sub> = m<sub>j</sub> + R
          </div>
        </section>
      </div>

      <hr className="border-slate-300 my-8" />

      {/* SECTION A: Single-Point Functions */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold text-slate-800 mb-2 flex items-center gap-2">
          <span role="img" aria-label="stop">🛑</span> SECTION A: SINGLE-POINT FUNCTIONS
        </h2>
        <p className="text-slate-600 mb-6 italic text-sm">The "Double-Masking" Demo. Simple rule: "Only accept if ID = 4"</p>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Match */}
          <div className="bg-emerald-50 border border-emerald-200 p-5 rounded-lg">
            <h4 className="font-bold text-emerald-800 border-b border-emerald-200 pb-2 mb-3">✅ Scenario 1: Data Matches (Output = 1)</h4>
            <p className="text-xs text-emerald-700 mb-3"><strong>Visual:</strong> The Box lands on the 1 spot.</p>
            <ul className="text-sm space-y-2 mb-4">
              <li><strong>Step 1 (Multiplier):</strong> Servers blindly multiply Box by 1. <em>(Box remains intact)</em>.</li>
              <li><strong>Step 2 (Anti-Mask):</strong> Servers spit out exact Pseudorandom Shares used by Client.</li>
              <li><strong>Step 3 (Unlocking):</strong> Servers apply shares. Static Mask is perfectly stripped away.</li>
            </ul>
            <div className="bg-emerald-100 p-2 rounded text-center font-mono text-sm font-semibold mb-2 text-emerald-900">
              1 × c<sub>j</sub> - R = m<sub>j</sub>
            </div>
            <p className="text-sm text-emerald-800 font-medium"><strong>Result:</strong> Servers are left holding the valid secret Message (m<sub>j</sub>).</p>
          </div>

          {/* No Match */}
          <div className="bg-red-50 border border-red-200 p-5 rounded-lg">
            <h4 className="font-bold text-red-800 border-b border-red-200 pb-2 mb-3">❌ Scenario 0: Data DOES NOT Match (Output = 0)</h4>
            <p className="text-xs text-red-700 mb-3"><strong>Visual:</strong> The Box lands on a 0 spot.</p>
            <ul className="text-sm space-y-2 mb-4">
              <li><strong>Step 1 (Multiplier):</strong> Servers blindly multiply Box by 0. <em>(Box disintegrates into dust)</em>.</li>
              <li><strong>Step 2 (Anti-Mask):</strong> Servers spit out random opposite shares (e.g., +5 and -5).</li>
              <li><strong>Step 3 (Unlocking):</strong> Opposite masks perfectly cancel each other out to 0.</li>
            </ul>
            <div className="bg-red-100 p-2 rounded text-center font-mono text-sm font-semibold mb-2 text-red-900">
              0 × c<sub>j</sub> - 0 = 0
            </div>
            <p className="text-sm text-red-800 font-medium"><strong>Result:</strong> The data is safely and completely wiped out.</p>
          </div>
        </div>
      </section>

      {/* SECTION B: Multi-Point Functions */}
      <section>
        <h2 className="text-2xl font-bold text-slate-800 mb-2 flex items-center gap-2">
          <span role="img" aria-label="globe">🌐</span> SECTION B: MULTI-POINT FUNCTIONS
        </h2>
        <p className="text-slate-600 mb-2 italic text-sm">The "Homomorphic Key" Demo. Complex rule: "Accept if ID = 4 OR 5 OR 6"</p>
        <div className="bg-amber-100 border-l-4 border-amber-500 text-amber-800 p-3 text-sm mb-6 rounded-r">
          <strong>Graphic Note:</strong> Emphasize that the simple trick above fails here because multiple "1" spots create inconsistent masks. We need the massive <em>"Homomorphic Master Key"</em>.
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Match */}
          <div className="bg-blue-50 border border-blue-200 p-5 rounded-lg">
            <h4 className="font-bold text-blue-800 border-b border-blue-200 pb-2 mb-3">🎯 Scenario 1: Data Hits ANY Valid Point (Output = 1)</h4>
            <p className="text-xs text-blue-700 mb-3"><strong>Visual:</strong> The Box lands on any of the 1 spots.</p>
            <ul className="text-sm space-y-2 mb-4">
              <li><strong>Step 1 (Multiplier):</strong> Servers multiply Box by 1 <em>(Box stays intact)</em>.</li>
              <li><strong>Step 2 (Extract Master Key):</strong> Servers correctly output secret pieces of the Master Key ([k<sup>h</sup><sub>k</sub>]).</li>
              <li><strong>Step 3 (Homomorphic Magic):</strong> Servers turn cranks on their pieces. Independent outputs perfectly combine to equal the exact Static Mask used.</li>
            </ul>
            <div className="bg-blue-100 p-2 rounded text-center font-mono text-sm font-semibold mb-2 text-blue-900">
              1 × c<sub>j</sub> - F(Key Pieces) = m<sub>j</sub> + tiny error
            </div>
            <p className="text-sm text-blue-800 font-medium"><strong>Result:</strong> Mask is stripped, leaving the Message (m<sub>j</sub>) plus a mathematically bounded tiny error.</p>
          </div>

          {/* No Match */}
          <div className="bg-slate-100 border border-slate-300 p-5 rounded-lg">
            <h4 className="font-bold text-slate-800 border-b border-slate-300 pb-2 mb-3">⛔ Scenario 0: Data Hits Invalid Point (Output = 0)</h4>
            <p className="text-xs text-slate-700 mb-3"><strong>Visual:</strong> The Box lands on a 0 spot.</p>
            <ul className="text-sm space-y-2 mb-4">
              <li><strong>Step 1 (Multiplier):</strong> Servers multiply Box by 0 <em>(Box disintegrates)</em>.</li>
              <li><strong>Step 2 (The 0-Key):</strong> Server Keys output secret shares of 0.</li>
              <li><strong>Step 3 (Special Zero-Key Property):</strong> Using the "Learning-With-Rounding" (LWR) math property, running the mask generator with a 0-key safely outputs exactly 0.</li>
            </ul>
            <div className="bg-slate-200 p-2 rounded text-center font-mono text-sm font-semibold mb-2 text-slate-900">
              0 × c<sub>j</sub> - F(0) = 0
            </div>
            <p className="text-sm text-slate-800 font-medium"><strong>Result:</strong> The 0 is subtracted from the destroyed box, perfectly hiding the rejected data.</p>
          </div>
        </div>
      </section>

    </div>
  );
};
// ============== END OF NEW CODE ==============

const defaultData = {
  title: "Streaming Function Secret Sharing",
  subtitle: "SFSS — A Cryptographic Protocol for Secure Data Filtering",
  part1: {
    label: "PART 1",
    title: "Single-Point Functions",
    subtitle: "Streaming DPF (SDPF)",
    example: '"Accept data only if ID = 4"',
    color: "#00D4FF",
    steps: [
      {
        num: "1",
        title: "Setup Phase",
        body: "Client creates DPF keys targeting single point α with embedded random payload r. Pseudorandom shares ⟦r⟧₀ and ⟦r⟧₁ are saved as secret PRF keys.",
      },
      {
        num: "2",
        title: "Streaming Encryption",
        body: "For each message mⱼ, client runs PRF twice to produce two masks. Formula: cⱼ = mⱼ − F(⟦r⟧₀, j) + F(−⟦r⟧₁, j)",
      },
      {
        num: "3",
        title: "Non-Interactive Evaluation",
        body: "Match (x=α): Keys output multiplier 1 + correct PRF shares → message recovered. No match (x≠α): Shares cancel out → result is exactly 0.",
      },
    ],
  },
  part2: {
    label: "PART 2",
    title: "Multi-Point Functions",
    subtitle: "Key-Homomorphic PRF",
    example: '"Accept data if ID is 4, 5, OR 6"',
    color: "#7B61FF",
    problem: "Double-masking from Part 1 fails — random shares become inconsistent across multiple target points.",
    steps: [
      {
        num: "1",
        title: "Setup Phase",
        body: "Client generates a master KH-PRF key k_kh. An augmented function outputs k_kh at EVERY valid target point, and 0 elsewhere. Distributed via FSS.",
      },
      {
        num: "2",
        title: "Streaming Encryption",
        body: "Much simpler: cⱼ = mⱼ + F(k_kh, j). One single mask from the master key — no double-masking needed.",
      },
      {
        num: "3",
        title: "Non-Interactive Evaluation",
        body: "Valid: Keys output shares of k_kh → KH property reconstructs mask → message recovered. Invalid: Shares of 0 + zero-key property → exactly 0.",
      },
    ],
  },
  comparison: [
    { feature: "Target Points", p1: "Single point α", p2: "Multiple points {α₁, α₂, ...}" },
    { feature: "Core Primitive", p1: "Standard PRF (double-masking)", p2: "Key-Homomorphic PRF" },
    { feature: "Encryption Formula", p1: "cⱼ = mⱼ − F(⟦r⟧₀, j) + F(−⟦r⟧₁, j)", p2: "cⱼ = mⱼ + F(k_kh, j)" },
    { feature: "Masks Used", p1: "Two masks (add + subtract)", p2: "One single mask" },
    { feature: "Key Distribution", p1: "PRF shares ⟦r⟧₀, ⟦r⟧₁ per point", p2: "Single master key k_kh" },
    { feature: "Valid Output", p1: "Exact mⱼ — no error", p2: "mⱼ + small bounded error e_kh" },
    { feature: "Invalid Output", p1: "Exactly 0 (shares cancel)", p2: "Exactly 0 (zero-key property)" },
    { feature: "Special Property", p1: "Key shares from DPF output", p2: "Homomorphic key splitting" },
  ],
};

function EditableText({ value, onChange, style, multiline, className }) {
  const [editing, setEditing] = useState(false);
  const [val, setVal] = useState(value);

  const commit = () => {
    onChange(val);
    setEditing(false);
  };

  if (editing) {
    return multiline ? (
      <textarea
        autoFocus
        value={val}
        onChange={e => setVal(e.target.value)}
        onBlur={commit}
        style={{
          ...style,
          background: "rgba(0,212,255,0.08)",
          border: "1px solid #00D4FF",
          borderRadius: 4,
          padding: "2px 6px",
          outline: "none",
          resize: "vertical",
          width: "100%",
          fontFamily: "inherit",
          minHeight: 60,
        }}
      />
    ) : (
      <input
        autoFocus
        value={val}
        onChange={e => setVal(e.target.value)}
        onBlur={commit}
        onKeyDown={e => e.key === "Enter" && commit()}
        style={{
          ...style,
          background: "rgba(0,212,255,0.08)",
          border: "1px solid #00D4FF",
          borderRadius: 4,
          padding: "2px 6px",
          outline: "none",
          width: "100%",
          fontFamily: "inherit",
        }}
      />
    );
  }

  return (
    <span
      onClick={() => setEditing(true)}
      title="Click to edit"
      className={className}
      style={{
        ...style,
        cursor: "text",
        borderBottom: "1px dashed rgba(0,212,255,0.3)",
        display: "inline-block",
        width: "100%",
        transition: "border-color 0.2s",
      }}
    >
      {value}
    </span>
  );
}

function StepCard({ step, color, onChange }) {
  return (
    <div
      style={{
        background: C.bgCard,
        border: `1.5px solid ${color}22`,
        borderLeft: `3px solid ${color}`,
        borderRadius: 10,
        padding: "14px 16px",
        flex: 1,
        minWidth: 0,
        position: "relative",
      }}
    >
      <div
        style={{
          width: 28,
          height: 28,
          borderRadius: "50%",
          background: color,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontWeight: 700,
          fontSize: 14,
          color: C.bg,
          marginBottom: 8,
          flexShrink: 0,
        }}
      >
        {step.num}
      </div>
      <div style={{ fontWeight: 700, fontSize: 13, color: C.white, marginBottom: 6 }}>
        <EditableText
          value={step.title}
          onChange={v => onChange({ ...step, title: v })}
          style={{ fontSize: 13, fontWeight: 700, color: C.white }}
        />
      </div>
      <div style={{ fontSize: 12, color: C.light, lineHeight: 1.55 }}>
        <EditableText
          value={step.body}
          onChange={v => onChange({ ...step, body: v })}
          style={{ fontSize: 12, color: C.light, lineHeight: 1.55 }}
          multiline
        />
      </div>
    </div>
  );
}

function PartSection({ data, onChange }) {
  return (
    <div
      style={{
        background: C.bgMid,
        border: `1.5px solid ${data.color}44`,
        borderRadius: 14,
        padding: "20px 22px",
        flex: 1,
        minWidth: 0,
      }}
    >
      {/* Header */}
      <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
        <div
          style={{
            background: data.color,
            color: C.bg,
            fontWeight: 700,
            fontSize: 11,
            padding: "3px 10px",
            borderRadius: 4,
            letterSpacing: 2,
            flexShrink: 0,
          }}
        >
          <EditableText
            value={data.label}
            onChange={v => onChange({ ...data, label: v })}
            style={{ fontSize: 11, fontWeight: 700, color: C.bg, letterSpacing: 2 }}
          />
        </div>
      </div>

      <div style={{ fontSize: 22, fontWeight: 800, color: C.white, marginBottom: 2 }}>
        <EditableText
          value={data.title}
          onChange={v => onChange({ ...data, title: v })}
          style={{ fontSize: 22, fontWeight: 800, color: C.white }}
        />
      </div>
      <div style={{ fontSize: 13, color: data.color, fontStyle: "italic", marginBottom: 6 }}>
        <EditableText
          value={data.subtitle}
          onChange={v => onChange({ ...data, subtitle: v })}
          style={{ fontSize: 13, color: data.color, fontStyle: "italic" }}
        />
      </div>
      <div
        style={{
          background: `${data.color}15`,
          border: `1px solid ${data.color}44`,
          borderRadius: 6,
          padding: "6px 10px",
          fontSize: 12,
          color: C.light,
          marginBottom: data.problem ? 12 : 16,
          fontStyle: "italic",
        }}
      >
        <EditableText
          value={data.example}
          onChange={v => onChange({ ...data, example: v })}
          style={{ fontSize: 12, color: C.light, fontStyle: "italic" }}
        />
      </div>

      {data.problem && (
        <div
          style={{
            background: "#FF6B6B18",
            border: "1px solid #FF6B6B44",
            borderRadius: 6,
            padding: "7px 10px",
            fontSize: 11.5,
            color: "#FF6B6B",
            marginBottom: 16,
          }}
        >
          <span style={{ fontWeight: 700 }}>⚠ Problem: </span>
          <EditableText
            value={data.problem}
            onChange={v => onChange({ ...data, problem: v })}
            style={{ fontSize: 11.5, color: "#FF6B6B" }}
            multiline
          />
        </div>
      )}

      {/* Steps */}
      <div style={{ display: "flex", gap: 10, flexDirection: "column" }}>
        {data.steps.map((step, i) => (
          <StepCard
            key={i}
            step={step}
            color={data.color}
            onChange={updated => {
              const steps = [...data.steps];
              steps[i] = updated;
              onChange({ ...data, steps });
            }}
          />
        ))}
      </div>
    </div>
  );
}

export default function SFSSInfographic() {
  const [d, setD] = useState(defaultData);
  const [activeTab, setActiveTab] = useState("full");

  const tabs = [
    { id: "full", label: "Full Overview" },
    { id: "part1", label: "Part 1: SDPF" },
    { id: "part2", label: "Part 2: KH-PRF" },
    { id: "compare", label: "Comparison" },
  ];

  return (
    <div
      style={{
        background: C.bg,
        minHeight: "100vh",
        fontFamily: "'Segoe UI', system-ui, sans-serif",
        color: C.white,
        padding: "24px 28px",
      }}
    >
      
      {/* Title */}
      <div style={{ textAlign: "center", marginBottom: 20 }}>
        <h1 style={{ fontSize: 28, fontWeight: 800, color: C.white, margin: "0 0 6px 0" }}>
          <EditableText
            value={d.title}
            onChange={v => setD({ ...d, title: v })}
            style={{ fontSize: 28, fontWeight: 800, color: C.white, textAlign: "center" }}
          />
        </h1>
        <div style={{ fontSize: 14, color: C.light }}>
          <EditableText
            value={d.subtitle}
            onChange={v => setD({ ...d, subtitle: v })}
            style={{ fontSize: 14, color: C.light }}
          />
        </div>
      </div>

      {/* Tabs */}
      <div style={{ display: "flex", gap: 8, justifyContent: "center", marginBottom: 22 }}>
        {tabs.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            style={{
              background: activeTab === tab.id ? C.cyan : C.bgCard,
              color: activeTab === tab.id ? C.bg : C.light,
              border: `1px solid ${activeTab === tab.id ? C.cyan : C.bgMid}`,
              borderRadius: 6,
              padding: "6px 14px",
              fontSize: 12,
              fontWeight: 600,
              cursor: "pointer",
              transition: "all 0.2s",
            }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Content */}
      {activeTab === "full" && (
        <div style={{ display: "flex", gap: 16 }}>
          <PartSection
            data={d.part1}
            onChange={p => setD({ ...d, part1: p })}
          />
          {/* VS divider */}
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              gap: 8,
              flexShrink: 0,
            }}
          >
            <div style={{ width: 1, flex: 1, background: "rgba(255,215,0,0.2)" }} />
            <div
              style={{
                width: 38,
                height: 38,
                borderRadius: "50%",
                background: C.bg,
                border: `2px solid ${C.gold}`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontSize: 13,
                fontWeight: 700,
                color: C.gold,
                flexShrink: 0,
              }}
            >
              VS
            </div>
            <div style={{ width: 1, flex: 1, background: "rgba(255,215,0,0.2)" }} />
          </div>
          <PartSection
            data={d.part2}
            onChange={p => setD({ ...d, part2: p })}
          />
        </div>
      )}

      {activeTab === "part1" && (
        <PartSection data={d.part1} onChange={p => setD({ ...d, part1: p })} />
      )}

      {activeTab === "part2" && (
        <PartSection data={d.part2} onChange={p => setD({ ...d, part2: p })} />
      )}

      {activeTab === "compare" && (
        <div>
          <div
            style={{
              background: C.bgMid,
              borderRadius: 14,
              overflow: "hidden",
              border: "1px solid rgba(255,255,255,0.06)",
            }}
          >
            {/* Table header */}
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "1.4fr 2fr 2fr",
                background: "rgba(13,24,38,0.8)",
              }}
            >
              {["Feature", "Part 1: SDPF", "Part 2: KH-PRF"].map((h, i) => (
                <div
                  key={i}
                  style={{
                    padding: "12px 18px",
                    fontSize: 13,
                    fontWeight: 700,
                    color: i === 0 ? C.gold : i === 1 ? C.cyan : C.purple,
                    borderBottom: `2px solid ${i === 0 ? C.gold : i === 1 ? C.cyan : C.purple}`,
                    textAlign: i === 0 ? "left" : "center",
                  }}
                >
                  {h}
                </div>
              ))}
            </div>
            {d.comparison.map((row, ri) => (
              <div
                key={ri}
                style={{
                  display: "grid",
                  gridTemplateColumns: "1.4fr 2fr 2fr",
                  background: ri % 2 === 0 ? C.bgCard : C.bgMid,
                  borderBottom: "1px solid rgba(255,255,255,0.04)",
                }}
              >
                <div style={{ padding: "12px 18px", fontSize: 13, fontWeight: 600, color: C.white }}>
                  <EditableText
                    value={row.feature}
                    onChange={v => {
                      const cmp = [...d.comparison];
                      cmp[ri] = { ...row, feature: v };
                      setD({ ...d, comparison: cmp });
                    }}
                    style={{ fontSize: 13, fontWeight: 600, color: C.white }}
                  />
                </div>
                <div style={{ padding: "12px 18px", fontSize: 12, color: C.light, textAlign: "center" }}>
                  <EditableText
                    value={row.p1}
                    onChange={v => {
                      const cmp = [...d.comparison];
                      cmp[ri] = { ...row, p1: v };
                      setD({ ...d, comparison: cmp });
                    }}
                    style={{ fontSize: 12, color: C.light, textAlign: "center" }}
                  />
                </div>
                <div style={{ padding: "12px 18px", fontSize: 12, color: C.light, textAlign: "center" }}>
                  <EditableText
                    value={row.p2}
                    onChange={v => {
                      const cmp = [...d.comparison];
                      cmp[ri] = { ...row, p2: v };
                      setD({ ...d, comparison: cmp });
                    }}
                    style={{ fontSize: 12, color: C.light, textAlign: "center" }}
                  />
                </div>
              </div>
            ))}
          </div>

          {/* Shared conclusion */}
          <div
            style={{
              background: "rgba(0,212,255,0.07)",
              border: "1px solid rgba(0,212,255,0.25)",
              borderRadius: 10,
              padding: "12px 18px",
              marginTop: 14,
              fontSize: 13,
              color: C.cyan,
              textAlign: "center",
              fontStyle: "italic",
            }}
          >
            Both constructions are non-interactive and provide perfect secrecy for non-target data.
          </div>
        </div>
      )}

      {/* Footer */}
      <div
        style={{
          marginTop: 24,
          textAlign: "center",
          fontSize: 11,
          color: C.muted,
          borderTop: "1px solid rgba(255,255,255,0.06)",
          paddingTop: 14,
        }}
      >
        SFSS — Streaming Function Secret Sharing .
      </div>
    </div>
  );
}
